apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: j7zba6035-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/quay_xjiang/rhtap-qe:75f6664c1114a61717d0c39a7a3bf426b06b12c5@sha256:e59c2b152fed3910639523a9e6e1e23eba8f417a545cd81ac105ffe527b1c266
          name: container-image
